ENERGIA_ENTRENAMIENTO = 0
MIN_AUMENTO_EXPERIENCIA = 0
MAX_AUMENTO_EXPERIENCIA = 0

MIN_AUMENTO_ENTRENAMIENTO = 0
MAX_AUMENTO_ENTRENAMIENTO = 0

AUMENTAR_ATAQUE_FUEGO = 0
AUMENTAR_VIDA_PLANTA = 0
AUMENTAR_VELOCIDAD_AGUA = 0

ENERGIA_CREAR_OBJETO = 0
PROB_EXITO_OBJETO = 0

GASTO_ENERGIA_BAYA = 0
PROB_EXITO_BAYA = 0

GASTO_ENERGIA_POCION = 0
PROB_EXITO_POCION = 0

AUMENTO_DEFENSA = 0
GASTO_ENERGIA_CARAMELO = 0
PROB_EXITO_CARAMELO = 0
