# En este archivo se definen los parametros

from random import randint, random

# PLANTAS

VIDA_PLANTA = 100
DANO_PROYECTIL = 10
INTERVALO_DISPARO = 1

RALENTIZAR_ZOMBIE = random()

INTERVALO_SOLES_GIRASOL = None
CANTIDAD_SOLES: int = 10


# PLANTA AZUL
RALENTIZAR_ZOMBIE = None
# INTERVALO_DISPARO = None
# VIDA_PLANTA = None

# GIRASOL
INTERVALO_SOLES_GIRASOL = None
# VIDA_PLANTA = None
CANTIDAD_SOLES = None

# PLANTA PATATA
# 2 * VIDA_PLANTA

# ZOMBIES
PONDERADOR_NOCTURNO = None
PONDERADOR_DIURNO = None

# zombie clásico
VELOCIDAD_ZOMBIE = None
DANO_MORDIDA = None
INTERVALO_TIEMPO_MORDIDA = None
VIDA_ZOMBIE = None

# zombie rápido
# 1.5 * VELOCIDAD_ZOMBIE

# SOLES
INTERVALOS_APARICION_SOLES = None

# JARDIN DE LA ABUELA
PONDERADOR_DIURNO = 0.9

# SALIDA NOCHE
PONDERADOR_NOCTURNO = 0.8

# PUNTAJE
PUNTAJE_ZOMBIE_DIURNO = None
PUNTAJE_ZOMBIE_NOCTURNO = None
